export type PublicLanguage = "en" | "fr";

export const marketplaceCopy = {
  en: {
    homes: "Find homes", alerts: "Match alerts", safer: "Why it’s safer", agents: "For agents", moderators: "For moderators", list: "List a home", fullCost: "See the full cost", beforeMove: "before you move.",
    freshIntro: "Fresh homes in Yaoundé and Douala. See total move-in cash, not rent alone.", searchKicker: "Start with your budget", where: "Where do you want to live?", city: "City", maxCash: "Maximum move-in cash", seeHomes: "See fresh homes", anonymous: "Search freely. Sign in to open a home.", totalCash: "Total Move-In Cash Required", viewCosts: "View photos, video and all costs", signIn: "Sign in to open this home.", breakdown: "Cost breakdown", mapPrivate: "The approximate map is available after sign-in.", french: "Français",
    routeFresh: "Fresh homes", routeAlerts: "Match alerts", routeTrust: "Trust rules", routeAgents: "Agent tools", routeModerators: "Field work", heroOverline: "Urban Cameroon / verified availability", freshnessRule: "Fresh for 14 days", landmarkMaps: "Landmark-only maps", searchPlaceholder: "Neighborhood or landmark", allCities: "All cities", anyAmount: "Any amount", routeOne: "Search by total cash", routeTwo: "Open a home for its map", routeThree: "Chat on WhatsApp", routeFour: "Visit before you pay",
    freshInventory: "Fresh homes", freshHeading: "Fresh homes only.", freshBody: "Agents reconfirm every 14 days. Unconfirmed homes leave public search.", publicVerifiedTitle: "Live homes are Field Moderator verified", publicVerifiedBody: "Live homes need a current on-site check and approved real media. Clearly labelled TEST DATA examples may appear for browsing; their imagery is illustrative, not real property evidence.", show: "Show", allFresh: "All fresh listings", checkingFreshness: "Checking freshness…", freshHome: "fresh home", freshHomes: "fresh homes", catalogueErrorTitle: "We could not load the catalogue.", catalogueErrorBody: "Please refresh. No inactive inventory is shown as a fallback.", emptyHomeTitle: "No fresh homes match this route yet.", emptyHomeBody: "Try another city or a larger total move-in budget. Agents use paid access before a transparent listing can enter review.", agentListHome: "I’m an agent — list a home", protectedMap: "Protected map", protectedMapHeading: "Open a home to see its landmark map.", protectedMapBody: "Video, photos and Total Move-In Cash are public. Sign in for itemised costs and the approximate map.",
    trustOverline: "How AHC protects you", trustHeadingOne: "Clear costs.", trustHeadingTwo: "Clearer rules.", trustIntro: "AHC shows costs and landmark areas—not compound doors. We do not hold rent or run in-app payments.", trustCostTitle: "One declared total", trustCostBody: "Rent, advance, deposit, agency, service and first-utility costs make one Total Move-In Cash figure.", trustPaidTitle: "Paid does not mean guaranteed", trustPaidBody: "Paid access means a reviewed submission—not a guarantee of the home, price, owner, or safety.", trustMapsTitle: "Maps protect the door", trustMapsBody: "Public pins show a 200–500m landmark area, never a compound door. Arrange exact access after a visit is agreed.", trustFreshTitle: "Freshness is enforced", trustFreshBody: "Listings without reconfirmation leave public search after 14 days.", trustDirectTitle: "Contact stays direct", trustDirectBody: "Chat with the agent on WhatsApp. Inspect first, agree in writing, keep receipts, and report changed terms.",
    agentOverline: "Agent tools", agentHeading: "Be clear. Earn attention.", agentBody: "Pay for Agent Access and a Listing Pass before review. Featured pins improve discovery; a physical badge follows a passed field check. Renters must still visit.", openAgent: "Open agent workspace", moderatorOverline: "Field Moderator work", moderatorHeading: "Inspect homes. Record evidence.", moderatorBody: "Field Moderators inspect listings and record visits. They receive 80% after an approved paid field check. Admin assigns this role.", moderatorSignIn: "Field Moderator sign in", footerPilot: "Yaoundé + Douala pilot", footerWarning: "Never pay before a visit, written agreement and receipt.",
    photosAvailable: "photos available", videoTour: "Walk-Thru video", photoPreview: "Photo preview", walkthroughPending: "Verified Walk-Thru not yet available", walkthroughPendingBody: "No public Field Moderator video has been approved for this listing. AHC does not substitute generated footage.", illustrativeTestMedia: "Illustrative TEST DATA media", illustrativeTestMediaBody: "Demo-only imagery. It is not a real home, a Field Moderator record, or a current availability claim.", featured: "Featured pin", listedBy: "Listed by", managingAgent: "Managing Agent", directOwner: "Direct From Owner", monthlyRent: "Monthly rent", notOnlyRent: "Not only the monthly rent.", guaranteedCash: "Guaranteed Total Cash", guaranteeNoDispute: "No upheld price or unofficial-fee dispute on record.", tarredGate: "Tarred to gate", dirtTrack: "Dirt-track approach", roadAssessed: "Road assessed", minTo: "min to", testTour: "Test Walk-Thru available", approvedTour: "Approved Walk-Thru available", landmarkArea: "landmark area", physicallyVerified: "Physically verified by AHC", notPhysicallyVerified: "Not yet physically verified", moderatorVisitPassed: "Field Moderator visit passed", noModeratorVisit: "Published after review; no on-site Field Moderator visit yet", reconfirmed: "Reconfirmed", daysLeft: "days left", dayLeft: "day left",
    rentAdvance: "Rent × {months} month(s)", securityDeposit: "Security deposit", agencyFee: "Agency fee", serviceFee: "Service fee", firstUtilities: "First-month utilities", closeDetails: "Close listing details", nearLandmark: "Near {landmark} · the public pin shows an approximate {radius}m landmark area, never the compound door.", mediaBeforeCosts: "Media is shown before the protected cost detail.", totalAdvice: "This is the cash the agent declared you need before moving in. Ask for written receipts and inspect the home before paying.", itemisedAfterTotal: "The itemised view follows the headline total.", landmarkView: "AHC / landmark view", approximateMap: "Approximate neighborhood map", mapProtection: "The pin remains limited to the landmark area; the compound door is never shown.", mapPrivacyKey: "Pin = 200–500m landmark area, never compound door", approximateLandmarkRadius: "Approximate landmark · {radius}m privacy radius", viewMore: "VIEW MORE", signInMap: "Sign in for the cost breakdown and map.", gateBody: "Video, photos and the full move-in total remain public. Sign-in protects the itemised costs and approximate landmark map.",
    reviewSample: "AHC / review sample", tourTest: "non-production Walk-Thru test", tourApproved: "approved Walk-Thru", testVideoHeading: "Test the full-detail video experience.", approvedVideoHeading: "See the verified home flow before arranging a visit.", testVideoBody: "This generated test clip demonstrates the non-production Seeker video flow only. It is not evidence of a real home, field visit, or availability.", approvedVideoBody: "This vertical clip was recorded during a passed Field Moderator visit. It is a public viewing aid, not the private proof package or an exact-address disclosure.",
    paidListingTitle: "What “paid listing” means", paidListingBody: "The agent paid for Agent Access and a Listing Pass before the listing entered moderator review. It is not a guarantee that the home, price, or agent is risk-free.", noRentTitle: "AHC does not hold your rent or deposit", noRentBody: "AHC is not an escrow, rent-collection, or deposit-holding service. Do not send tenancy money to AHC or to anyone claiming to collect it for AHC.", protectVisit: "Protect your visit", protectVisitBody: "Do not send a deposit before you inspect the home, agree terms in writing, and receive a receipt. AHC never asks seekers to pay an Agent or Owner a platform fee; report any unofficial AHC-fee demand here.", physicalBadge: "Physical verification badge", freshnessCheck: "Freshness check", freshnessBody: "This listing leaves public search after 14 days without agent reconfirmation.", intentNote: "AHC records only this authenticated contact intent before opening WhatsApp. It does not read your messages or claim a booking or payment outcome.", sharePreview: "Share preview", reportIssue: "Report an issue", chatWhatsApp: "Chat on WhatsApp", reviewQuestion: "What needs review?", inaccurateCost: "Inaccurate Total Move-In Cash", unavailable: "Home is no longer available", misleading: "Listing details do not match", unofficialFee: "Someone requested an unofficial AHC fee", otherIssue: "Another issue", whatHappened: "What happened?", reportPlaceholder: "For example: the agent requested 12 months’ advance instead of the listed amount...", reportSafety: "Three distinct inaccurate-cost or unavailable-listing reports automatically remove this listing from public search pending Admin review. Unofficial-fee reports are separately queued for payment-fraud review.", cancel: "Cancel", sendingReport: "Sending report…", sendReport: "Send report",
    alertSignin: "Open any listing and sign in to save a private WhatsApp match alert.", quietAlerts: "QUIET MATCH ALERTS", alertHeading: "Good homes should find you.", alertBody: "Set your limits once. AHC evaluates newly moderator-approved homes against your opt-in criteria. Your number is never shown to agents or landlords.", setAlert: "Set a WhatsApp alert", activeAlerts: "active private alerts", matchingHomes: "matching homes queued in your history", providerPending: "Provider activation pending", optInOnly: "OPT-IN ONLY", silentAlert: "Set a silent match alert", alertDialogBody: "AHC will match only newly moderator-approved listings. We will not sell or reveal this number to an Agent or Owner. Delivery will remain queued until an approved WhatsApp Business provider is live.", whatsappNumber: "WhatsApp number", neighborhoodOptional: "Neighbourhood (optional)", maxMonthly: "Max monthly rent (XAF)", saveAlert: "Save private alert", savingConsent: "Saving consent…",
    concierge: "Viewing concierge", reserveWindow: "Reserve a viewing window", appointmentAvailable: "Send a time window. The Agent must accept it before your number is released and before access details are agreed.", appointmentUnavailable: "Appointments open only for physically verified, live homes.", preferredStart: "Preferred start", preferredEnd: "Preferred end", contactRoute: "Contact route", phoneCall: "Phone call", yourNumber: "Your {route} number", noteAgent: "Note for the Agent", optional: "optional", notePlaceholder: "For example: I can arrive after work and would like to confirm the water point.", appointmentPrivacy: "AHC keeps your number private until the Agent confirms this request. The public map remains landmark-only.", sendingRequest: "Sending request…", requestViewing: "Request this viewing", requestError: "Unable to request this viewing", cancelError: "Unable to cancel", cancelAppointmentNote: "Seeker cancelled this viewing request.", organiseVisits: "Keep your home visits organized.", historyAnonymous: "Sign in when you open a property to request a viewing time. AHC does not publish your contact number or exact compound access details.", scheduledVisits: "Your scheduled property visits.", historyBody: "Requests are private until accepted. Bring the listed cost breakdown and do not pay before your inspection.", loadingRequests: "Loading your viewing requests…", agentNote: "Agent note", noAppointments: "No active viewing requests. Open a verified home to reserve a viewing time.",
    privateView: "AHC PRIVATE VIEW", walkBeforeTaxi: "Walk through it before you taxi there.", railBody: "Short, unedited vertical clips are captured by a Field Moderator during a passed on-site check. Exact compound locations remain private.", verifiedMotion: "VERIFIED MOTION", moderatorTours: "Moderator-verified video walk-throughs", moderatorTour: "Moderator walk-through", monthly: "monthly", openFullDetails: "View full home details", demoOnly: "Product demonstration only", reviewSampleTitle: "See the viewing standard—without pretending.", demoBody: "This short clip is an AI-generated, non-production product demonstration. It is not a home for rent, not a moderator visit, and does not have a property-detail, map pin, contact button, price, or verification badge.", realRule: "Real listing rule", realRuleBody: "Only an on-site Field Moderator’s unedited 15–30 second vertical clip, linked to a passed verification record, may appear in the verified discovery rail.",
    createAccount: "Create account", fullName: "Full name", professionalName: "Your professional name", taxpayerNumber: "Taxpayer number", taxpayerPlaceholder: "Taxpayer identification number", workProof: "Proof of work reference URL", workProofPlaceholder: "Brokerage, employer, or work proof URL", governmentId: "Government ID — JPG images only", idUploadNote: "Upload the front, back, and a face-view image. These files are private and are not shown on public listings.", idFront: "ID front", idBack: "ID back", faceView: "Face view", email: "Email address", password: "Password", passwordNew: "At least 10 characters", passwordExisting: "Your AHC password", passwordShow: "Show", hide: "Hide", wait: "Please wait…", signInAHC: "Sign in to AHC", seekerAccount: "AHC seeker account", seekerRegister: "Create AHC seeker account", seekerNote: "Create a free AHC seeker account to open full property details, contact agents, and report changed terms. A Manus account is not required.",
  },
  fr: {
    homes: "Trouver un logement", alerts: "Alertes de recherche", safer: "Pourquoi c’est plus sûr", agents: "Pour les agents", moderators: "Pour les modérateurs", list: "Publier un logement", fullCost: "Voyez le coût total", beforeMove: "avant de déménager.",
    freshIntro: "Des logements récents à Yaoundé et Douala. Voyez le montant total, pas seulement le loyer.", searchKicker: "Commencez avec votre budget", where: "Où voulez-vous habiter ?", city: "Ville", maxCash: "Budget maximum à l’entrée", seeHomes: "Voir les logements récents", anonymous: "Cherchez librement. Connectez-vous pour ouvrir un logement.", totalCash: "Montant total à prévoir", viewCosts: "Voir photos, vidéo et tous les coûts", signIn: "Connectez-vous pour ouvrir ce logement.", breakdown: "Détail des coûts", mapPrivate: "La carte approximative est disponible après connexion.", french: "English",
    routeFresh: "Logements récents", routeAlerts: "Alertes", routeTrust: "Règles de confiance", routeAgents: "Outils agent", routeModerators: "Travail terrain", heroOverline: "Cameroun urbain / disponibilité vérifiée", freshnessRule: "Frais pendant 14 jours", landmarkMaps: "Cartes par repères seulement", searchPlaceholder: "Quartier ou repère", allCities: "Toutes les villes", anyAmount: "Tout budget", routeOne: "Chercher selon le montant total", routeTwo: "Ouvrir un logement pour sa carte", routeThree: "Écrire sur WhatsApp", routeFour: "Visiter avant de payer",
    freshInventory: "Logements récents", freshHeading: "Seulement des logements récents.", freshBody: "Les agents reconfirment tous les 14 jours. Sinon, l’annonce quitte la recherche publique.", publicVerifiedTitle: "Les logements réels sont vérifiés par un modérateur terrain", publicVerifiedBody: "Un logement réel nécessite une visite sur place actuelle et des médias réels approuvés. Des exemples clairement marqués TEST DATA peuvent apparaître pour la navigation ; leurs images sont illustratives et ne constituent pas une preuve de logement réel.", show: "Afficher", allFresh: "Toutes les annonces récentes", checkingFreshness: "Vérification de la fraîcheur…", freshHome: "logement récent", freshHomes: "logements récents", catalogueErrorTitle: "Le catalogue n’a pas pu être chargé.", catalogueErrorBody: "Veuillez actualiser. Aucun inventaire inactif n’est affiché en remplacement.", emptyHomeTitle: "Aucun logement récent ne correspond encore à cette recherche.", emptyHomeBody: "Essayez une autre ville ou un budget total plus élevé. Les agents utilisent un accès payant avant qu’une annonce transparente puisse entrer en contrôle.", agentListHome: "Je suis agent — publier un logement", protectedMap: "Carte protégée", protectedMapHeading: "Ouvrez un logement pour voir sa carte par repère.", protectedMapBody: "La vidéo, les photos et le montant total restent publics. Connectez-vous pour le détail des coûts et la carte approximative.",
    trustOverline: "Comment AHC vous protège", trustHeadingOne: "Coûts clairs.", trustHeadingTwo: "Règles claires.", trustIntro: "AHC montre les coûts et les repères, pas la porte exacte. Nous ne gardons ni loyers ni paiements.", trustCostTitle: "Un seul montant déclaré", trustCostBody: "Loyer, avance, caution, agence, service et premières charges forment un total à prévoir.", trustPaidTitle: "Payer ne garantit pas tout", trustPaidBody: "L’accès payant signifie une soumission contrôlée, pas une garantie du logement, du prix, du propriétaire ou de votre sécurité.", trustMapsTitle: "Les cartes protègent la porte", trustMapsBody: "Les repères publics montrent une zone de 200–500 m, jamais la porte. Convenez de l’accès exact après avoir fixé la visite.", trustFreshTitle: "La fraîcheur est appliquée", trustFreshBody: "Sans reconfirmation, l’annonce quitte la recherche publique après 14 jours.", trustDirectTitle: "Le contact reste direct", trustDirectBody: "Écrivez à l’agent sur WhatsApp. Inspectez d’abord, convenez des termes par écrit, gardez les reçus et signalez les changements.",
    agentOverline: "Outils agent", agentHeading: "Soyez clair. Gagnez de l’attention.", agentBody: "Payez l’Accès Agent et un Pass d’annonce avant le contrôle. Les repères mis en avant améliorent la visibilité; un badge physique suit une visite validée. Le locataire doit toujours visiter.", openAgent: "Ouvrir l’espace agent", moderatorOverline: "Travail du modérateur terrain", moderatorHeading: "Inspectez. Enregistrez les preuves.", moderatorBody: "Les modérateurs terrain inspectent les logements et enregistrent les visites. Ils reçoivent 80 % après une vérification payante approuvée. L’administrateur attribue ce rôle.", moderatorSignIn: "Connexion modérateur terrain", footerPilot: "Pilote Yaoundé + Douala", footerWarning: "Ne payez jamais avant une visite, un accord écrit et un reçu.",
    photosAvailable: "photos disponibles", videoTour: "Vidéo de visite", photoPreview: "Aperçu photo", walkthroughPending: "Vidéo de visite vérifiée pas encore disponible", walkthroughPendingBody: "Aucune vidéo publique du modérateur terrain n’a encore été approuvée pour cette annonce. AHC ne remplace pas cette preuve par une vidéo générée.", illustrativeTestMedia: "Médias illustratifs de DONNÉES TEST", illustrativeTestMediaBody: "Images réservées à la démonstration. Elles ne représentent ni un vrai logement, ni un dossier de modérateur terrain, ni une disponibilité actuelle.", featured: "Repère mis en avant", listedBy: "Publié par", managingAgent: "Agent gestionnaire", directOwner: "Propriétaire direct", monthlyRent: "Loyer mensuel", notOnlyRent: "Pas seulement le loyer mensuel.", guaranteedCash: "Montant total garanti", guaranteeNoDispute: "Aucun litige confirmé sur le prix ou des frais non officiels.", tarredGate: "Route goudronnée jusqu’à l’entrée", dirtTrack: "Accès par piste", roadAssessed: "Accès routier évalué", minTo: "min vers", testTour: "Visite test disponible", approvedTour: "Visite approuvée disponible", landmarkArea: "zone de repère", physicallyVerified: "Vérifié physiquement par AHC", notPhysicallyVerified: "Pas encore vérifié physiquement", moderatorVisitPassed: "Visite du modérateur terrain validée", noModeratorVisit: "Publié après contrôle; aucune visite sur place du modérateur terrain", reconfirmed: "Reconfirmé", daysLeft: "jours restants", dayLeft: "jour restant",
    rentAdvance: "Loyer × {months} mois", securityDeposit: "Caution", agencyFee: "Frais d’agence", serviceFee: "Frais de service", firstUtilities: "Premières charges mensuelles", closeDetails: "Fermer les détails de l’annonce", nearLandmark: "Près de {landmark} · le repère public montre une zone approximative de {radius} m, jamais la porte de la concession.", mediaBeforeCosts: "Les médias sont présentés avant le détail protégé des coûts.", totalAdvice: "C’est le montant déclaré par l’agent avant l’emménagement. Demandez des reçus écrits et inspectez le logement avant de payer.", itemisedAfterTotal: "Le détail par poste suit le montant principal.", landmarkView: "AHC / vue par repère", approximateMap: "Carte approximative du quartier", mapProtection: "Le point reste limité à la zone du repère; la porte de la concession n’est jamais affichée.", mapPrivacyKey: "Repère = zone de 200–500 m, jamais la porte", approximateLandmarkRadius: "Repère approximatif · rayon de confidentialité de {radius} m", viewMore: "VOIR PLUS", signInMap: "Connectez-vous pour le détail des coûts et la carte.", gateBody: "La vidéo, les photos et le montant total restent publics. La connexion protège le détail des coûts et la carte approximative par repère.",
    reviewSample: "AHC / exemple de contrôle", tourTest: "test de visite hors production", tourApproved: "visite approuvée", testVideoHeading: "Testez l’expérience vidéo avec détails complets.", approvedVideoHeading: "Voyez le parcours vérifié avant de fixer une visite.", testVideoBody: "Cette vidéo test générée démontre uniquement le parcours chercheur hors production. Elle ne prouve ni un vrai logement, ni une visite terrain, ni une disponibilité.", approvedVideoBody: "Cette vidéo verticale a été enregistrée pendant une visite validée du modérateur terrain. C’est une aide publique pour la visite, pas un dossier de preuve privé ni une divulgation d’adresse exacte.",
    paidListingTitle: "Ce que signifie « annonce payante »", paidListingBody: "L’agent a payé l’Accès Agent et un Pass d’annonce avant que l’annonce entre en contrôle par un modérateur. Cela ne garantit pas que le logement, le prix ou l’agent soit sans risque.", noRentTitle: "AHC ne conserve ni votre loyer ni votre caution", noRentBody: "AHC n’est ni un séquestre, ni un service de collecte de loyer ou de dépôt. N’envoyez pas d’argent locatif à AHC ni à une personne qui prétend le collecter pour AHC.", protectVisit: "Protégez votre visite", protectVisitBody: "N’envoyez pas de caution avant d’inspecter le logement, de convenir des termes par écrit et de recevoir un reçu. AHC ne demande jamais aux chercheurs de payer des frais de plateforme à un agent ou à un propriétaire; signalez toute demande de frais AHC non officielle ici.", physicalBadge: "Badge de vérification physique", freshnessCheck: "Contrôle de fraîcheur", freshnessBody: "Cette annonce quitte la recherche publique après 14 jours sans reconfirmation de l’agent.", intentNote: "AHC enregistre uniquement cette intention de contact authentifiée avant d’ouvrir WhatsApp. Il ne lit pas vos messages et ne prétend pas connaître l’issue d’une réservation ou d’un paiement.", sharePreview: "Partager l’aperçu", reportIssue: "Signaler un problème", chatWhatsApp: "Discuter sur WhatsApp", reviewQuestion: "Que faut-il examiner ?", inaccurateCost: "Montant total à prévoir inexact", unavailable: "Logement non disponible", misleading: "Les détails ne correspondent pas", unofficialFee: "Demande de frais AHC non officiels", otherIssue: "Autre problème", whatHappened: "Que s’est-il passé ?", reportPlaceholder: "Par exemple : l’agent a demandé 12 mois d’avance au lieu du montant indiqué...", reportSafety: "Trois signalements distincts de coût inexact ou d’annonce indisponible retirent automatiquement cette annonce de la recherche publique en attente d’un examen administrateur. Les signalements de frais non officiels sont traités séparément pour fraude de paiement.", cancel: "Annuler", sendingReport: "Envoi du signalement…", sendReport: "Envoyer le signalement",
    alertSignin: "Ouvrez une annonce et connectez-vous pour enregistrer une alerte WhatsApp privée.", quietAlerts: "ALERTES DISCRÈTES", alertHeading: "Les bons logements devraient vous trouver.", alertBody: "Définissez vos limites une fois. AHC évalue les nouveaux logements approuvés par un modérateur selon vos critères. Votre numéro n’est jamais montré aux agents ni aux propriétaires.", setAlert: "Créer une alerte WhatsApp", activeAlerts: "alertes privées actives", matchingHomes: "logements correspondants dans votre historique", providerPending: "Activation du fournisseur en attente", optInOnly: "AVEC CONSENTEMENT", silentAlert: "Créer une alerte discrète", alertDialogBody: "AHC ne comparera que les nouvelles annonces approuvées par un modérateur. Nous ne vendrons ni ne révélerons ce numéro à un agent ou à un propriétaire. La livraison reste en attente jusqu’à l’activation d’un fournisseur WhatsApp Business approuvé.", whatsappNumber: "Numéro WhatsApp", neighborhoodOptional: "Quartier (facultatif)", maxMonthly: "Loyer mensuel maximal (XAF)", saveAlert: "Enregistrer l’alerte privée", savingConsent: "Enregistrement du consentement…",
    concierge: "Organisation des visites", reserveWindow: "Réserver un créneau de visite", appointmentAvailable: "Envoyez un créneau. L’agent doit l’accepter avant que votre numéro soit transmis et que les détails d’accès soient convenus.", appointmentUnavailable: "Les rendez-vous sont ouverts seulement pour les logements disponibles et physiquement vérifiés.", preferredStart: "Début souhaité", preferredEnd: "Fin souhaitée", contactRoute: "Moyen de contact", phoneCall: "Appel téléphonique", yourNumber: "Votre numéro {route}", noteAgent: "Note pour l’agent", optional: "facultatif", notePlaceholder: "Par exemple : je peux arriver après le travail et souhaite confirmer le point d’eau.", appointmentPrivacy: "AHC conserve votre numéro privé jusqu’à ce que l’agent confirme cette demande. La carte publique reste limitée au repère.", sendingRequest: "Envoi de la demande…", requestViewing: "Demander cette visite", requestError: "Impossible de demander cette visite", cancelError: "Impossible d’annuler", cancelAppointmentNote: "Le chercheur a annulé cette demande de visite.", organiseVisits: "Organisez vos visites de logement.", historyAnonymous: "Connectez-vous en ouvrant un logement pour demander un créneau de visite. AHC ne publie ni votre numéro ni les détails exacts d’accès à la concession.", scheduledVisits: "Vos visites de logement planifiées.", historyBody: "Les demandes restent privées jusqu’à acceptation. Apportez le détail des coûts indiqué et ne payez pas avant votre inspection.", loadingRequests: "Chargement de vos demandes de visite…", agentNote: "Note de l’agent", noAppointments: "Aucune demande de visite active. Ouvrez un logement vérifié pour réserver un créneau de visite.",
    privateView: "AHC / VISITE PRIVÉE", walkBeforeTaxi: "Visitez avant de payer le taxi.", railBody: "De courtes vidéos verticales non éditées sont capturées par un modérateur terrain lors d’une visite sur place validée. Les emplacements exacts des concessions restent privés.", verifiedMotion: "MOUVEMENT VÉRIFIÉ", moderatorTours: "Vidéos de visite vérifiées par un modérateur", moderatorTour: "Visite du modérateur", monthly: "par mois", openFullDetails: "Voir les détails complets", demoOnly: "Démonstration produit seulement", reviewSampleTitle: "Voyez la norme de visite — sans faire semblant.", demoBody: "Cette courte vidéo est une démonstration produit générée par IA et hors production. Ce n’est pas un logement à louer, pas une visite de modérateur, et elle n’a ni détail de propriété, ni repère carte, ni bouton de contact, ni prix, ni badge de vérification.", realRule: "Règle pour une vraie annonce", realRuleBody: "Seule une vidéo verticale non éditée de 15–30 secondes d’un modérateur terrain présent sur place, liée à un dossier de vérification validé, peut apparaître dans le fil de découverte vérifié.",
    createAccount: "Créer un compte", fullName: "Nom complet", professionalName: "Votre nom professionnel", taxpayerNumber: "Numéro de contribuable", taxpayerPlaceholder: "Numéro d’identification fiscale", workProof: "URL de référence professionnelle", workProofPlaceholder: "URL du courtier, de l’employeur ou d’une preuve de travail", governmentId: "Pièce d’identité — images JPG uniquement", idUploadNote: "Téléversez le recto, le verso et une image de votre visage. Ces fichiers sont privés et ne sont pas affichés sur les annonces publiques.", idFront: "Recto", idBack: "Verso", faceView: "Vue du visage", email: "Adresse e-mail", password: "Mot de passe", passwordNew: "Au moins 10 caractères", passwordExisting: "Votre mot de passe AHC", passwordShow: "Afficher", hide: "Masquer", wait: "Veuillez patienter…", signInAHC: "Se connecter à AHC", seekerAccount: "Compte chercheur AHC", seekerRegister: "Créer un compte chercheur AHC", seekerNote: "Créez gratuitement un compte chercheur AHC pour ouvrir les détails complets, contacter les agents et signaler les changements de conditions. Un compte Manus n’est pas nécessaire.",
  },
} as const;

export const catalogueInteractionCopy = {
  en: {
    sort: "Sort homes",
    catalogueOrder: "Catalogue order",
    priceLowToHigh: "Total cash: low to high",
    newestFirst: "Newest first",
    saveFavorite: "Save to favourites",
    removeFavorite: "Remove from favourites",
    favoritesSignIn: "Sign in to save homes to your favourites.",
    areaAmenities: "Area amenities",
    viewDetails: "View details",
  },
  fr: {
    sort: "Trier les logements",
    catalogueOrder: "Ordre du catalogue",
    priceLowToHigh: "Coût total : croissant",
    newestFirst: "Les plus récents d’abord",
    saveFavorite: "Enregistrer en favoris",
    removeFavorite: "Retirer des favoris",
    favoritesSignIn: "Connectez-vous pour enregistrer des logements en favoris.",
    areaAmenities: "Commodités du quartier",
    viewDetails: "Voir les détails",
  },
} as const;

export type MarketplaceCopyKey = keyof typeof marketplaceCopy.en;

export function text(language: PublicLanguage, key: MarketplaceCopyKey) {
  return marketplaceCopy[language][key];
}

export function interpolate(value: string, variables: Record<string, string | number>) {
  return Object.entries(variables).reduce((result, [key, replacement]) => result.replaceAll(`{${key}}`, String(replacement)), value);
}
