/**
 * French equivalents for AHC-owned interface language. This intentionally excludes property
 * descriptions, user names, messages, identifiers and other user-entered content.
 */
const interfaceFrench: Record<string, string> = {
  "Affordable Housing Cameroon": "Logement abordable Cameroun",
  "My AHC account": "Mon compte AHC",
  "Your dashboard": "Votre tableau de bord",
  "Back to homes": "Retour aux logements",
  "Marketplace": "Marché immobilier",
  "Dashboard": "Tableau de bord",
  "Profile": "Profil",
  "Your AHC profile": "Votre profil AHC",
  "Blank profile picture": "Photo de profil vide",
  "Choose picture": "Choisir une photo",
  "Remove picture": "Supprimer la photo",
  "Removing…": "Suppression…",
  "Uploading…": "Téléversement…",
  "Display name": "Nom affiché",
  "Login email": "E-mail de connexion",
  "Not recorded": "Non enregistré",
  "Save profile": "Enregistrer le profil",
  "Saving profile…": "Enregistrement du profil…",
  "My platform-service orders": "Mes commandes de services de plateforme",
  "No platform-service orders yet": "Aucune commande de service de plateforme pour le moment",
  "Email preferences": "Préférences e-mail",
  "Account updates": "Mises à jour du compte",
  "Match alerts": "Alertes de correspondance",
  "Saved homes": "Logements enregistrés",
  "Recent browsing": "Consultations récentes",
  "Safety report updates": "Mises à jour des signalements de sécurité",
  "Mark as read": "Marquer comme lu",
  "Reviewed": "Examiné",
  "Report reviewed": "Signalement examiné",
  "No reviewed safety-report updates yet": "Aucune mise à jour de signalement examinée pour le moment",
  "Sign in to view your dashboard": "Connectez-vous pour voir votre tableau de bord",
  "Preparing your customer dashboard…": "Préparation de votre tableau de bord locataire…",
  "We could not load your dashboard": "Nous n’avons pas pu charger votre tableau de bord",
  "Try again": "Réessayer",
  "Retrying…": "Nouvel essai…",
  "Profile saved": "Profil enregistré",
  "Profile picture removed": "Photo de profil supprimée",
  "Profile picture updated": "Photo de profil mise à jour",
  "Email preferences saved": "Préférences e-mail enregistrées",
  "Safety report update marked as read.": "Mise à jour du signalement de sécurité marquée comme lue.",
  "We could not save your profile": "Nous n’avons pas pu enregistrer votre profil",
  "We could not remove your picture": "Nous n’avons pas pu supprimer votre photo",
  "We could not save email preferences": "Nous n’avons pas pu enregistrer vos préférences e-mail",
  "We could not update this report notice": "Nous n’avons pas pu mettre à jour cet avis de signalement",
  "Choose a small JPG or PNG": "Choisissez un petit JPG ou PNG",
  "TEST ONLY": "TEST UNIQUEMENT",
  "Checkout-feedback simulator": "Simulateur de retour de paiement",
  "Ready for a safe test.": "Prêt pour un test sûr.",
  "Testing…": "Test en cours…",
  "Simulate success": "Simuler la réussite",
  "Simulate temporary error": "Simuler une erreur temporaire",
  "Retry successful path": "Réessayer le parcours de réussite",
  "Official service receipt": "Reçu officiel de service",
  "Print receipt": "Imprimer le reçu",
  "Close": "Fermer",
  "Order": "Commande",
  "Created": "Créée",
  "Amount": "Montant",
  "Status": "Statut",
  "Payment reference": "Référence de paiement",
  "No payment": "Aucun paiement",
  "Admin": "Admin",
  "Administrator": "Administrateur",
  "Field Moderator": "Modérateur de terrain",
  "Moderator": "Modérateur",
  "Operations": "Opérations",
  "Admin access": "Accès Admin",
  "Moderator access": "Accès Modérateur",
  "Sign in": "Se connecter",
  "Sign in to open this home.": "Connectez-vous pour ouvrir ce logement.",
  "Create account": "Créer un compte",
  "E-MAIL ADDRESS": "ADRESSE E-MAIL",
  "PASSWORD": "MOT DE PASSE",
  "Your AHC password": "Votre mot de passe AHC",
  "Show": "Afficher",
  "Secure staff route": "Accès sécurisé du personnel",
  "FIELD WORK": "TRAVAIL DE TERRAIN",
  "GOVERNANCE": "GOUVERNANCE",
  "Sign in to field operations.": "Connectez-vous aux opérations terrain.",
  "Sign in to platform administration.": "Connectez-vous à l’administration de la plateforme.",
  "Sign in to Field Operations": "Se connecter aux opérations terrain",
  "Sign in to Admin": "Se connecter à l’Admin",
  "Admin accounts are provisioned only by the AHC system owner or an authorised Admin. Public registration never grants platform authority.": "Les comptes Admin sont créés uniquement par le propriétaire du système AHC ou un Admin autorisé. Une inscription publique ne donne jamais l’autorité sur la plateforme.",
  "Moderator accounts are assigned by an AHC Admin. Public registration never grants staff authority.": "Les comptes Modérateur sont attribués par un Admin AHC. Une inscription publique ne donne jamais l’autorité du personnel.",
  "Agent accounts are created directly with AHC. A Manus account is not required. Repeated incorrect passwords are temporarily locked to protect accounts.": "Les comptes Agent sont créés directement avec AHC. Un compte Manus n’est pas requis. Les mots de passe incorrects répétés sont temporairement bloqués pour protéger les comptes.",
  "Your sign-in uses an AHC account. A Manus account is not required. The Admin route is intentionally not linked from public pages.": "Votre connexion utilise un compte AHC. Un compte Manus n’est pas requis. La route Admin n’est volontairement pas liée depuis les pages publiques.",
  "Use an explicit AHC account sign-in. A Manus or preview session does not unlock this workspace.": "Utilisez une connexion explicite à un compte AHC. Une session Manus ou d’aperçu ne déverrouille pas cet espace.",
  "The Admin workspace controls roles, platform settings, payment reconciliation, trust-risk review, safety holds, and held commission approval. It is reserved for accounts deliberately assigned the Admin role.": "L’espace Admin contrôle les rôles, les paramètres de la plateforme, le rapprochement des paiements, l’examen des risques de confiance, les retenues de sécurité et l’approbation des commissions retenues. Il est réservé aux comptes auxquels le rôle Admin a été attribué délibérément.",
  "Moderators review submitted listings, record on-site inspection outcomes and private evidence, and earn the recorded share only after verification evidence and any required audit receive Admin approval. Platform service-order reconciliation is an Admin-only finance control. This work area is for staff intentionally assigned by an AHC Admin.": "Les Modérateurs examinent les annonces soumises, consignent les résultats d’inspection sur place et les preuves privées, et ne reçoivent la part enregistrée qu’après l’approbation Admin des preuves de vérification et de tout audit requis. Le rapprochement des commandes de services de plateforme est un contrôle financier réservé à l’Admin. Cet espace est réservé au personnel désigné par un Admin AHC.",
  "Sign out": "Se déconnecter",
  "Signed out of AHC": "Déconnexion d’AHC effectuée",
  "Open my AHC dashboard": "Ouvrir mon tableau de bord AHC",
  "Checking secure access…": "Vérification de l’accès sécurisé…",
  "Redirecting to your permitted workspace…": "Redirection vers votre espace autorisé…",
  "Protected route": "Route protégée",
  "Review": "Examiner",
  "Review complete": "Examen terminé",
  "Complete review": "Terminer l’examen",
  "Review report": "Examiner le signalement",
  "Review notes": "Notes d’examen",
  "Reviewer note": "Note de l’examinateur",
  "Verification": "Vérification",
  "Verification evidence": "Preuves de vérification",
  "Physical verification": "Vérification physique",
  "Verified": "Vérifié",
  "Unverified": "Non vérifié",
  "Pending": "En attente",
  "Approved": "Approuvé",
  "Rejected": "Rejeté",
  "Declined": "Refusé",
  "Confirm": "Confirmer",
  "Cancel": "Annuler",
  "Save": "Enregistrer",
  "Submit": "Envoyer",
  "Submit for review": "Envoyer pour examen",
  "Upload": "Téléverser",
  "Upload evidence": "Téléverser les preuves",
  "Choose file": "Choisir un fichier",
  "No file chosen": "Aucun fichier choisi",
  "Loading…": "Chargement…",
  "Loading": "Chargement",
  "No results": "Aucun résultat",
  "No records yet": "Aucun enregistrement pour le moment",
  "No reports yet": "Aucun signalement pour le moment",
  "No listings yet": "Aucune annonce pour le moment",
  "Refresh": "Actualiser",
  "Refresh now": "Actualiser maintenant",
  "Search": "Rechercher",
  "Filter": "Filtrer",
  "Clear filters": "Effacer les filtres",
  "All": "Tous",
  "Required": "Obligatoire",
  "Optional": "Facultatif",
  "Name": "Nom",
  "Email": "E-mail",
  "Phone": "Téléphone",
  "WhatsApp number": "Numéro WhatsApp",
  "City": "Ville",
  "Neighbourhood": "Quartier",
  "Landmark": "Repère",
  "Property type": "Type de logement",
  "Bedrooms": "Chambres",
  "Monthly rent": "Loyer mensuel",
  "Advance months": "Mois d’avance",
  "Security deposit": "Caution",
  "Agency fee": "Frais d’agence",
  "Service fee": "Frais de service",
  "Utilities": "Services publics",
  "Available from": "Disponible à partir du",
  "Listing title": "Titre de l’annonce",
  "Description": "Description",
  "Notes": "Notes",
  "Reason": "Motif",
  "Report": "Signaler",
  "Report listing": "Signaler l’annonce",
  "Report submitted": "Signalement envoyé",
  "Safety": "Sécurité",
  "Account": "Compte",
  "Role": "Rôle",
  "Access": "Accès",
  "Payment": "Paiement",
  "Payment reconciliation": "Rapprochement des paiements",
  "Transaction reference": "Référence de transaction",
  "Cash-flow audit": "Audit des flux de trésorerie",
  "Commission ledger": "Registre des commissions",
  "Export CSV": "Exporter en CSV",
  "Owner alerts": "Alertes du propriétaire",
  "WhatsApp leads": "Prospects WhatsApp",
  "Account protection": "Protection du compte",
  "Assign role": "Attribuer le rôle",
  "Direct from owner": "Direct du propriétaire",
  "Managing Agent": "Agent gestionnaire",
  "Reconfirmed": "Reconfirmé",
  "days ago": "jours auparavant",
  "today": "aujourd’hui",
  "yesterday": "hier",
  "English": "Anglais",
  "French": "Français",
  "Language": "Langue",
  "Light": "Clair",
  "Dark": "Sombre",
  "Switch to light mode": "Passer au mode clair",
  "Switch to dark mode": "Passer au mode sombre",
  "View details": "Voir les détails",
  "View full details": "Voir tous les détails",
  "Request a viewing": "Demander une visite",
  "Chat on WhatsApp": "Discuter sur WhatsApp",
  "Back": "Retour",
  "Continue": "Continuer",
  "Success": "Réussi",
  "Error": "Erreur",
  "Retry": "Réessayer",
  "Security verification failed. Please complete the challenge and try again.": "La vérification de sécurité a échoué. Veuillez terminer le contrôle et réessayer.",
  "Security verification is not configured.": "La vérification de sécurité n’est pas configurée.",
};

const orderedEnglishTerms = Object.keys(interfaceFrench).sort((left, right) => right.length - left.length);

export function translateAhcInterfaceText(value: string, language: "en" | "fr") {
  if (language === "en" || !value.trim()) return value;
  let translated = value;
  for (const english of orderedEnglishTerms) {
    if (!translated.includes(english)) continue;
    translated = translated.split(english).join(interfaceFrench[english]);
  }
  return translated;
}

export function isAhcInterfaceTranslation(value: string) {
  return orderedEnglishTerms.some(english => value.includes(english));
}
